//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace JupiterSIPClient1.wsReference {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="JupiterWSBinding", Namespace="http://jupiterws.dna.com/soap/JupiterWS")]
    public partial class JupiterWS : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback getDateTimeOperationCompleted;
        
        private System.Threading.SendOrPostCallback jAgentLoginOperationCompleted;
        
        private System.Threading.SendOrPostCallback jAgentGetStatesOperationCompleted;
        
        private System.Threading.SendOrPostCallback jAgentChangeStateOperationCompleted;
        
        private System.Threading.SendOrPostCallback jAgentGetAnnounceOperationCompleted;
        
        private System.Threading.SendOrPostCallback jAgentGetAnnounceFilesOperationCompleted;
        
        private System.Threading.SendOrPostCallback jAgentRemoveAnnounceOperationCompleted;
        
        private System.Threading.SendOrPostCallback jAgentAddAnnounceOperationCompleted;
        
        private System.Threading.SendOrPostCallback jAgentSetAnnounceStateOperationCompleted;
        
        private System.Threading.SendOrPostCallback jAgentSetSoundOptionOperationCompleted;
        
        private System.Threading.SendOrPostCallback jGetPublicIpOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public JupiterWS() {
            this.Url = global::JupiterSIPClient1.Properties.Settings.Default.JupiterSIPClient1_wsReference_JupiterWS;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event getDateTimeCompletedEventHandler getDateTimeCompleted;
        
        /// <remarks/>
        public event jAgentLoginCompletedEventHandler jAgentLoginCompleted;
        
        /// <remarks/>
        public event jAgentGetStatesCompletedEventHandler jAgentGetStatesCompleted;
        
        /// <remarks/>
        public event jAgentChangeStateCompletedEventHandler jAgentChangeStateCompleted;
        
        /// <remarks/>
        public event jAgentGetAnnounceCompletedEventHandler jAgentGetAnnounceCompleted;
        
        /// <remarks/>
        public event jAgentGetAnnounceFilesCompletedEventHandler jAgentGetAnnounceFilesCompleted;
        
        /// <remarks/>
        public event jAgentRemoveAnnounceCompletedEventHandler jAgentRemoveAnnounceCompleted;
        
        /// <remarks/>
        public event jAgentAddAnnounceCompletedEventHandler jAgentAddAnnounceCompleted;
        
        /// <remarks/>
        public event jAgentSetAnnounceStateCompletedEventHandler jAgentSetAnnounceStateCompleted;
        
        /// <remarks/>
        public event jAgentSetSoundOptionCompletedEventHandler jAgentSetSoundOptionCompleted;
        
        /// <remarks/>
        public event jGetPublicIpCompletedEventHandler jGetPublicIpCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://jupiterws.dna.com/ws.php/getDateTime", RequestNamespace="", ResponseNamespace="")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string getDateTime() {
            object[] results = this.Invoke("getDateTime", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getDateTimeAsync() {
            this.getDateTimeAsync(null);
        }
        
        /// <remarks/>
        public void getDateTimeAsync(object userState) {
            if ((this.getDateTimeOperationCompleted == null)) {
                this.getDateTimeOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetDateTimeOperationCompleted);
            }
            this.InvokeAsync("getDateTime", new object[0], this.getDateTimeOperationCompleted, userState);
        }
        
        private void OngetDateTimeOperationCompleted(object arg) {
            if ((this.getDateTimeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getDateTimeCompleted(this, new getDateTimeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://jupiterws.dna.com/ws.php/j.AgentLogin", RequestNamespace="", ResponseNamespace="")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public AgentLogin jAgentLogin(string p) {
            object[] results = this.Invoke("jAgentLogin", new object[] {
                        p});
            return ((AgentLogin)(results[0]));
        }
        
        /// <remarks/>
        public void jAgentLoginAsync(string p) {
            this.jAgentLoginAsync(p, null);
        }
        
        /// <remarks/>
        public void jAgentLoginAsync(string p, object userState) {
            if ((this.jAgentLoginOperationCompleted == null)) {
                this.jAgentLoginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnjAgentLoginOperationCompleted);
            }
            this.InvokeAsync("jAgentLogin", new object[] {
                        p}, this.jAgentLoginOperationCompleted, userState);
        }
        
        private void OnjAgentLoginOperationCompleted(object arg) {
            if ((this.jAgentLoginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.jAgentLoginCompleted(this, new jAgentLoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://jupiterws.dna.com/ws.php/j.AgentGetStates", RequestNamespace="", ResponseNamespace="")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public AgentGetStates jAgentGetStates(string p) {
            object[] results = this.Invoke("jAgentGetStates", new object[] {
                        p});
            return ((AgentGetStates)(results[0]));
        }
        
        /// <remarks/>
        public void jAgentGetStatesAsync(string p) {
            this.jAgentGetStatesAsync(p, null);
        }
        
        /// <remarks/>
        public void jAgentGetStatesAsync(string p, object userState) {
            if ((this.jAgentGetStatesOperationCompleted == null)) {
                this.jAgentGetStatesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnjAgentGetStatesOperationCompleted);
            }
            this.InvokeAsync("jAgentGetStates", new object[] {
                        p}, this.jAgentGetStatesOperationCompleted, userState);
        }
        
        private void OnjAgentGetStatesOperationCompleted(object arg) {
            if ((this.jAgentGetStatesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.jAgentGetStatesCompleted(this, new jAgentGetStatesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://jupiterws.dna.com/ws.php/j.AgentChangeState", RequestNamespace="", ResponseNamespace="")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public AgentChangeState jAgentChangeState(string p) {
            object[] results = this.Invoke("jAgentChangeState", new object[] {
                        p});
            return ((AgentChangeState)(results[0]));
        }
        
        /// <remarks/>
        public void jAgentChangeStateAsync(string p) {
            this.jAgentChangeStateAsync(p, null);
        }
        
        /// <remarks/>
        public void jAgentChangeStateAsync(string p, object userState) {
            if ((this.jAgentChangeStateOperationCompleted == null)) {
                this.jAgentChangeStateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnjAgentChangeStateOperationCompleted);
            }
            this.InvokeAsync("jAgentChangeState", new object[] {
                        p}, this.jAgentChangeStateOperationCompleted, userState);
        }
        
        private void OnjAgentChangeStateOperationCompleted(object arg) {
            if ((this.jAgentChangeStateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.jAgentChangeStateCompleted(this, new jAgentChangeStateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://jupiterws.dna.com/ws.php/j.AgentGetAnnounce", RequestNamespace="", ResponseNamespace="")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public AgentGetAnnounce jAgentGetAnnounce(string p) {
            object[] results = this.Invoke("jAgentGetAnnounce", new object[] {
                        p});
            return ((AgentGetAnnounce)(results[0]));
        }
        
        /// <remarks/>
        public void jAgentGetAnnounceAsync(string p) {
            this.jAgentGetAnnounceAsync(p, null);
        }
        
        /// <remarks/>
        public void jAgentGetAnnounceAsync(string p, object userState) {
            if ((this.jAgentGetAnnounceOperationCompleted == null)) {
                this.jAgentGetAnnounceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnjAgentGetAnnounceOperationCompleted);
            }
            this.InvokeAsync("jAgentGetAnnounce", new object[] {
                        p}, this.jAgentGetAnnounceOperationCompleted, userState);
        }
        
        private void OnjAgentGetAnnounceOperationCompleted(object arg) {
            if ((this.jAgentGetAnnounceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.jAgentGetAnnounceCompleted(this, new jAgentGetAnnounceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://jupiterws.dna.com/ws.php/j.AgentGetAnnounceFiles", RequestNamespace="", ResponseNamespace="")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public AgentGetAnnounceFiles jAgentGetAnnounceFiles(string p) {
            object[] results = this.Invoke("jAgentGetAnnounceFiles", new object[] {
                        p});
            return ((AgentGetAnnounceFiles)(results[0]));
        }
        
        /// <remarks/>
        public void jAgentGetAnnounceFilesAsync(string p) {
            this.jAgentGetAnnounceFilesAsync(p, null);
        }
        
        /// <remarks/>
        public void jAgentGetAnnounceFilesAsync(string p, object userState) {
            if ((this.jAgentGetAnnounceFilesOperationCompleted == null)) {
                this.jAgentGetAnnounceFilesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnjAgentGetAnnounceFilesOperationCompleted);
            }
            this.InvokeAsync("jAgentGetAnnounceFiles", new object[] {
                        p}, this.jAgentGetAnnounceFilesOperationCompleted, userState);
        }
        
        private void OnjAgentGetAnnounceFilesOperationCompleted(object arg) {
            if ((this.jAgentGetAnnounceFilesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.jAgentGetAnnounceFilesCompleted(this, new jAgentGetAnnounceFilesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://jupiterws.dna.com/ws.php/j.AgentRemoveAnnounce", RequestNamespace="", ResponseNamespace="")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public AgentRemoveAnnounce jAgentRemoveAnnounce(string p) {
            object[] results = this.Invoke("jAgentRemoveAnnounce", new object[] {
                        p});
            return ((AgentRemoveAnnounce)(results[0]));
        }
        
        /// <remarks/>
        public void jAgentRemoveAnnounceAsync(string p) {
            this.jAgentRemoveAnnounceAsync(p, null);
        }
        
        /// <remarks/>
        public void jAgentRemoveAnnounceAsync(string p, object userState) {
            if ((this.jAgentRemoveAnnounceOperationCompleted == null)) {
                this.jAgentRemoveAnnounceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnjAgentRemoveAnnounceOperationCompleted);
            }
            this.InvokeAsync("jAgentRemoveAnnounce", new object[] {
                        p}, this.jAgentRemoveAnnounceOperationCompleted, userState);
        }
        
        private void OnjAgentRemoveAnnounceOperationCompleted(object arg) {
            if ((this.jAgentRemoveAnnounceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.jAgentRemoveAnnounceCompleted(this, new jAgentRemoveAnnounceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://jupiterws.dna.com/ws.php/j.AgentAddAnnounce", RequestNamespace="", ResponseNamespace="")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public AgentAddAnnounce jAgentAddAnnounce(string p, [System.Xml.Serialization.SoapElementAttribute(DataType="base64Binary")] byte[] fileContent) {
            object[] results = this.Invoke("jAgentAddAnnounce", new object[] {
                        p,
                        fileContent});
            return ((AgentAddAnnounce)(results[0]));
        }
        
        /// <remarks/>
        public void jAgentAddAnnounceAsync(string p, byte[] fileContent) {
            this.jAgentAddAnnounceAsync(p, fileContent, null);
        }
        
        /// <remarks/>
        public void jAgentAddAnnounceAsync(string p, byte[] fileContent, object userState) {
            if ((this.jAgentAddAnnounceOperationCompleted == null)) {
                this.jAgentAddAnnounceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnjAgentAddAnnounceOperationCompleted);
            }
            this.InvokeAsync("jAgentAddAnnounce", new object[] {
                        p,
                        fileContent}, this.jAgentAddAnnounceOperationCompleted, userState);
        }
        
        private void OnjAgentAddAnnounceOperationCompleted(object arg) {
            if ((this.jAgentAddAnnounceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.jAgentAddAnnounceCompleted(this, new jAgentAddAnnounceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://jupiterws.dna.com/ws.php/j.AgentSetAnnounceState", RequestNamespace="", ResponseNamespace="")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public AgentSetAnnounceState jAgentSetAnnounceState(string p) {
            object[] results = this.Invoke("jAgentSetAnnounceState", new object[] {
                        p});
            return ((AgentSetAnnounceState)(results[0]));
        }
        
        /// <remarks/>
        public void jAgentSetAnnounceStateAsync(string p) {
            this.jAgentSetAnnounceStateAsync(p, null);
        }
        
        /// <remarks/>
        public void jAgentSetAnnounceStateAsync(string p, object userState) {
            if ((this.jAgentSetAnnounceStateOperationCompleted == null)) {
                this.jAgentSetAnnounceStateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnjAgentSetAnnounceStateOperationCompleted);
            }
            this.InvokeAsync("jAgentSetAnnounceState", new object[] {
                        p}, this.jAgentSetAnnounceStateOperationCompleted, userState);
        }
        
        private void OnjAgentSetAnnounceStateOperationCompleted(object arg) {
            if ((this.jAgentSetAnnounceStateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.jAgentSetAnnounceStateCompleted(this, new jAgentSetAnnounceStateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://jupiterws.dna.com/ws.php/j.AgentSetSoundOption", RequestNamespace="", ResponseNamespace="")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public AgentSetSoundOption jAgentSetSoundOption(string p) {
            object[] results = this.Invoke("jAgentSetSoundOption", new object[] {
                        p});
            return ((AgentSetSoundOption)(results[0]));
        }
        
        /// <remarks/>
        public void jAgentSetSoundOptionAsync(string p) {
            this.jAgentSetSoundOptionAsync(p, null);
        }
        
        /// <remarks/>
        public void jAgentSetSoundOptionAsync(string p, object userState) {
            if ((this.jAgentSetSoundOptionOperationCompleted == null)) {
                this.jAgentSetSoundOptionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnjAgentSetSoundOptionOperationCompleted);
            }
            this.InvokeAsync("jAgentSetSoundOption", new object[] {
                        p}, this.jAgentSetSoundOptionOperationCompleted, userState);
        }
        
        private void OnjAgentSetSoundOptionOperationCompleted(object arg) {
            if ((this.jAgentSetSoundOptionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.jAgentSetSoundOptionCompleted(this, new jAgentSetSoundOptionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://jupiterws.dna.com/ws.php/j.GetPublicIp", RequestNamespace="", ResponseNamespace="")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public GetPublicIp jGetPublicIp(string p) {
            object[] results = this.Invoke("jGetPublicIp", new object[] {
                        p});
            return ((GetPublicIp)(results[0]));
        }
        
        /// <remarks/>
        public void jGetPublicIpAsync(string p) {
            this.jGetPublicIpAsync(p, null);
        }
        
        /// <remarks/>
        public void jGetPublicIpAsync(string p, object userState) {
            if ((this.jGetPublicIpOperationCompleted == null)) {
                this.jGetPublicIpOperationCompleted = new System.Threading.SendOrPostCallback(this.OnjGetPublicIpOperationCompleted);
            }
            this.InvokeAsync("jGetPublicIp", new object[] {
                        p}, this.jGetPublicIpOperationCompleted, userState);
        }
        
        private void OnjGetPublicIpOperationCompleted(object arg) {
            if ((this.jGetPublicIpCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.jGetPublicIpCompleted(this, new jGetPublicIpCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.79.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://jupiterws.dna.com/soap/JupiterWS")]
    public partial class AgentLogin {
        
        private string resultField;
        
        private string agentIdField;
        
        private string domainNameField;
        
        private string sessionIdField;
        
        private string sipUserNameField;
        
        private string sipAuthField;
        
        private string sipPasswordField;
        
        private string sipServerIpField;
        
        private string sipServerHostnameField;
        
        private string sipServerPortField;
        
        private string statesField;
        
        private string skillsField;
        
        private string defMicrophoneField;
        
        private string defSpeakerField;
        
        private string defAudioCodecField;
        
        private string defVideoCodecField;
        
        /// <remarks/>
        public string result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer")]
        public string agentId {
            get {
                return this.agentIdField;
            }
            set {
                this.agentIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer")]
        public string domainName {
            get {
                return this.domainNameField;
            }
            set {
                this.domainNameField = value;
            }
        }
        
        /// <remarks/>
        public string sessionId {
            get {
                return this.sessionIdField;
            }
            set {
                this.sessionIdField = value;
            }
        }
        
        /// <remarks/>
        public string sipUserName {
            get {
                return this.sipUserNameField;
            }
            set {
                this.sipUserNameField = value;
            }
        }
        
        /// <remarks/>
        public string sipAuth {
            get {
                return this.sipAuthField;
            }
            set {
                this.sipAuthField = value;
            }
        }
        
        /// <remarks/>
        public string sipPassword {
            get {
                return this.sipPasswordField;
            }
            set {
                this.sipPasswordField = value;
            }
        }
        
        /// <remarks/>
        public string sipServerIp {
            get {
                return this.sipServerIpField;
            }
            set {
                this.sipServerIpField = value;
            }
        }
        
        /// <remarks/>
        public string sipServerHostname {
            get {
                return this.sipServerHostnameField;
            }
            set {
                this.sipServerHostnameField = value;
            }
        }
        
        /// <remarks/>
        public string sipServerPort {
            get {
                return this.sipServerPortField;
            }
            set {
                this.sipServerPortField = value;
            }
        }
        
        /// <remarks/>
        public string states {
            get {
                return this.statesField;
            }
            set {
                this.statesField = value;
            }
        }
        
        /// <remarks/>
        public string skills {
            get {
                return this.skillsField;
            }
            set {
                this.skillsField = value;
            }
        }
        
        /// <remarks/>
        public string defMicrophone {
            get {
                return this.defMicrophoneField;
            }
            set {
                this.defMicrophoneField = value;
            }
        }
        
        /// <remarks/>
        public string defSpeaker {
            get {
                return this.defSpeakerField;
            }
            set {
                this.defSpeakerField = value;
            }
        }
        
        /// <remarks/>
        public string defAudioCodec {
            get {
                return this.defAudioCodecField;
            }
            set {
                this.defAudioCodecField = value;
            }
        }
        
        /// <remarks/>
        public string defVideoCodec {
            get {
                return this.defVideoCodecField;
            }
            set {
                this.defVideoCodecField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.79.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://jupiterws.dna.com/soap/JupiterWS")]
    public partial class GetPublicIp {
        
        private string resultField;
        
        private string publicIpField;
        
        /// <remarks/>
        public string result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
        
        /// <remarks/>
        public string publicIp {
            get {
                return this.publicIpField;
            }
            set {
                this.publicIpField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.79.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://jupiterws.dna.com/soap/JupiterWS")]
    public partial class AgentSetSoundOption {
        
        private string resultField;
        
        private string reasonField;
        
        /// <remarks/>
        public string result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
        
        /// <remarks/>
        public string reason {
            get {
                return this.reasonField;
            }
            set {
                this.reasonField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.79.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://jupiterws.dna.com/soap/JupiterWS")]
    public partial class AgentSetAnnounceState {
        
        private string resultField;
        
        private string reasonField;
        
        /// <remarks/>
        public string result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
        
        /// <remarks/>
        public string reason {
            get {
                return this.reasonField;
            }
            set {
                this.reasonField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.79.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://jupiterws.dna.com/soap/JupiterWS")]
    public partial class AgentAddAnnounce {
        
        private string resultField;
        
        private string reasonField;
        
        /// <remarks/>
        public string result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
        
        /// <remarks/>
        public string reason {
            get {
                return this.reasonField;
            }
            set {
                this.reasonField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.79.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://jupiterws.dna.com/soap/JupiterWS")]
    public partial class AgentRemoveAnnounce {
        
        private string resultField;
        
        private string reasonField;
        
        /// <remarks/>
        public string result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
        
        /// <remarks/>
        public string reason {
            get {
                return this.reasonField;
            }
            set {
                this.reasonField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.79.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://jupiterws.dna.com/soap/JupiterWS")]
    public partial class AgentGetAnnounceFiles {
        
        private string resultField;
        
        private string reasonField;
        
        private string recordFile1Field;
        
        private byte[] recordContent1Field;
        
        private string recordFile2Field;
        
        private byte[] recordContent2Field;
        
        private string recordFile3Field;
        
        private byte[] recordContent3Field;
        
        private string recordFile4Field;
        
        private byte[] recordContent4Field;
        
        private string recordFile5Field;
        
        private byte[] recordContent5Field;
        
        private string recordFile6Field;
        
        private byte[] recordContent6Field;
        
        private string recordFile7Field;
        
        private byte[] recordContent7Field;
        
        private string recordFile8Field;
        
        private byte[] recordContent8Field;
        
        private string recordFile9Field;
        
        private byte[] recordContent9Field;
        
        private string recordFile10Field;
        
        private byte[] recordContent10Field;
        
        /// <remarks/>
        public string result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
        
        /// <remarks/>
        public string reason {
            get {
                return this.reasonField;
            }
            set {
                this.reasonField = value;
            }
        }
        
        /// <remarks/>
        public string recordFile1 {
            get {
                return this.recordFile1Field;
            }
            set {
                this.recordFile1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="base64Binary")]
        public byte[] recordContent1 {
            get {
                return this.recordContent1Field;
            }
            set {
                this.recordContent1Field = value;
            }
        }
        
        /// <remarks/>
        public string recordFile2 {
            get {
                return this.recordFile2Field;
            }
            set {
                this.recordFile2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="base64Binary")]
        public byte[] recordContent2 {
            get {
                return this.recordContent2Field;
            }
            set {
                this.recordContent2Field = value;
            }
        }
        
        /// <remarks/>
        public string recordFile3 {
            get {
                return this.recordFile3Field;
            }
            set {
                this.recordFile3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="base64Binary")]
        public byte[] recordContent3 {
            get {
                return this.recordContent3Field;
            }
            set {
                this.recordContent3Field = value;
            }
        }
        
        /// <remarks/>
        public string recordFile4 {
            get {
                return this.recordFile4Field;
            }
            set {
                this.recordFile4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="base64Binary")]
        public byte[] recordContent4 {
            get {
                return this.recordContent4Field;
            }
            set {
                this.recordContent4Field = value;
            }
        }
        
        /// <remarks/>
        public string recordFile5 {
            get {
                return this.recordFile5Field;
            }
            set {
                this.recordFile5Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="base64Binary")]
        public byte[] recordContent5 {
            get {
                return this.recordContent5Field;
            }
            set {
                this.recordContent5Field = value;
            }
        }
        
        /// <remarks/>
        public string recordFile6 {
            get {
                return this.recordFile6Field;
            }
            set {
                this.recordFile6Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="base64Binary")]
        public byte[] recordContent6 {
            get {
                return this.recordContent6Field;
            }
            set {
                this.recordContent6Field = value;
            }
        }
        
        /// <remarks/>
        public string recordFile7 {
            get {
                return this.recordFile7Field;
            }
            set {
                this.recordFile7Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="base64Binary")]
        public byte[] recordContent7 {
            get {
                return this.recordContent7Field;
            }
            set {
                this.recordContent7Field = value;
            }
        }
        
        /// <remarks/>
        public string recordFile8 {
            get {
                return this.recordFile8Field;
            }
            set {
                this.recordFile8Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="base64Binary")]
        public byte[] recordContent8 {
            get {
                return this.recordContent8Field;
            }
            set {
                this.recordContent8Field = value;
            }
        }
        
        /// <remarks/>
        public string recordFile9 {
            get {
                return this.recordFile9Field;
            }
            set {
                this.recordFile9Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="base64Binary")]
        public byte[] recordContent9 {
            get {
                return this.recordContent9Field;
            }
            set {
                this.recordContent9Field = value;
            }
        }
        
        /// <remarks/>
        public string recordFile10 {
            get {
                return this.recordFile10Field;
            }
            set {
                this.recordFile10Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="base64Binary")]
        public byte[] recordContent10 {
            get {
                return this.recordContent10Field;
            }
            set {
                this.recordContent10Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.79.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://jupiterws.dna.com/soap/JupiterWS")]
    public partial class AgentGetAnnounce {
        
        private string resultField;
        
        private string reasonField;
        
        private string recordsField;
        
        /// <remarks/>
        public string result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
        
        /// <remarks/>
        public string reason {
            get {
                return this.reasonField;
            }
            set {
                this.reasonField = value;
            }
        }
        
        /// <remarks/>
        public string records {
            get {
                return this.recordsField;
            }
            set {
                this.recordsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.79.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://jupiterws.dna.com/soap/JupiterWS")]
    public partial class AgentChangeState {
        
        private string resultField;
        
        private string reasonField;
        
        /// <remarks/>
        public string result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
        
        /// <remarks/>
        public string reason {
            get {
                return this.reasonField;
            }
            set {
                this.reasonField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.79.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://jupiterws.dna.com/soap/JupiterWS")]
    public partial class AgentGetStates {
        
        private string statesField;
        
        /// <remarks/>
        public string states {
            get {
                return this.statesField;
            }
            set {
                this.statesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void getDateTimeCompletedEventHandler(object sender, getDateTimeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getDateTimeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getDateTimeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void jAgentLoginCompletedEventHandler(object sender, jAgentLoginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class jAgentLoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal jAgentLoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AgentLogin Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AgentLogin)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void jAgentGetStatesCompletedEventHandler(object sender, jAgentGetStatesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class jAgentGetStatesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal jAgentGetStatesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AgentGetStates Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AgentGetStates)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void jAgentChangeStateCompletedEventHandler(object sender, jAgentChangeStateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class jAgentChangeStateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal jAgentChangeStateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AgentChangeState Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AgentChangeState)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void jAgentGetAnnounceCompletedEventHandler(object sender, jAgentGetAnnounceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class jAgentGetAnnounceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal jAgentGetAnnounceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AgentGetAnnounce Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AgentGetAnnounce)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void jAgentGetAnnounceFilesCompletedEventHandler(object sender, jAgentGetAnnounceFilesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class jAgentGetAnnounceFilesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal jAgentGetAnnounceFilesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AgentGetAnnounceFiles Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AgentGetAnnounceFiles)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void jAgentRemoveAnnounceCompletedEventHandler(object sender, jAgentRemoveAnnounceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class jAgentRemoveAnnounceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal jAgentRemoveAnnounceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AgentRemoveAnnounce Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AgentRemoveAnnounce)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void jAgentAddAnnounceCompletedEventHandler(object sender, jAgentAddAnnounceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class jAgentAddAnnounceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal jAgentAddAnnounceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AgentAddAnnounce Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AgentAddAnnounce)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void jAgentSetAnnounceStateCompletedEventHandler(object sender, jAgentSetAnnounceStateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class jAgentSetAnnounceStateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal jAgentSetAnnounceStateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AgentSetAnnounceState Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AgentSetAnnounceState)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void jAgentSetSoundOptionCompletedEventHandler(object sender, jAgentSetSoundOptionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class jAgentSetSoundOptionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal jAgentSetSoundOptionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AgentSetSoundOption Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AgentSetSoundOption)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void jGetPublicIpCompletedEventHandler(object sender, jGetPublicIpCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class jGetPublicIpCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal jGetPublicIpCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetPublicIp Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetPublicIp)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591